services:
  vantage-api-mock-nextjs:
    container_name: vantage-api-mock-nextjs
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        BUILD_PROFILE: ${BUILD_PROFILE}
    image: vantage-api-mock-nextjs:0.0.1
    restart: unless-stopped
    ports:
      - '8676:8676'
    command: npm run start:prod
